#!/bin/bash

# Use XDG_CONFIG_HOME if set, otherwise default to ~/.config
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

ln -sf "$(pwd)/init.lua" "${CONFIG_HOME}/nvim/init.lua"

echo "Successfully set up the config!"

